### ISSUE TITLE
Omit example of certificate enrollment

### ISSUE THREAD

**Issue by gselander** [EricssonResearch/ace-ake-authz#12]
> In this document we consider the target interaction for which authorization is needed to be "enrollment", for example joining a network for the first time (e.g. [[RFC9031](file:///Users/eragose/Git/ace-ake-authz/draft-selander-lake-authz.html#RFC9031)]), or certificate enrollment (such as [[I-D.selander-ace-coap-est-oscore](file:///Users/eragose/Git/ace-ake-authz/draft-selander-lake-authz.html#I-D.selander-ace-coap-est-oscore)]), but it can be applied to authorize other target interactions.

Since certificate enrollment can also be carried out with CSR in EAD_3, I propose we remove this part to avoid confusion:

> or certificate enrollment (such as [[I-D.selander-ace-coap-est-oscore](file:///Users/eragose/Git/ace-ake-authz/draft-selander-lake-authz.html#I-D.selander-ace-coap-est-oscore)]),

**Comment by malishav** [comment]
Removed this mention with 094b91583d

There is one more mention of CSR in 4.4.3.1:

> EAD_3 MAY contain a certificate enrollment request, see e.g. CSR specified in {{I-D.mattsson-cose-cbor-cert compress}}, or other request which the device is now authorized to make.

Do you want to remove this mention as well?

**Comment by gselander** [comment]
I propose we keep that. I was concerned about having both descriptions could be confusing. Since this describes another use case of EAD, which is relevant to LAKE, I think is the most relevant to keep.
